---
- name: Create a VM
  hosts: localhost

  vars:
    datacenter: 'Labvmware'
    esxi_host: 192.168.121.130
    notes: 'Created by Ansible_SERVER'
    datastore: datastore_vmlabesx001
    osid: debian9_64Guest

  tasks:
  - name: Create a VMTEST
    vmware_guest:
      hostname: 192.168.121.130
      username: root
      password: '@Password1234'
      validate_certs: no
      folder: /vm
      guest_id: debian9Guest
      name: VMTEST23
      state: present
      disk:
      - size_gb: 1
        type: thin
        datastore: datastore_vmlabesx001
      hardware:
        memory_mb: 512
        num_cpus: 1
        scsi: paravirtual
      networks:
      - name: 'VM Network'
      wait_for_ip_address: no
    register: deploy
