---
- name: Installing VLC MSI
  hosts: all
  tasks:
  - name: Download the VLC Installer
    win_get_url:
      dest: C:\ansible_examples\vlc-3.0.8-win64.msi
  - name: Install MSI
    win_package:
      path: c:\ansible_examples\vlc-3.0.8-win64.msi
      state: present
      arguments: /qn